--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: drugs; Type: TABLE; Schema: public; Owner: brown
--

CREATE TABLE public.drugs (
    id integer NOT NULL,
    buyer_id integer NOT NULL,
    category character varying(255)[] NOT NULL,
    date date NOT NULL,
    description character varying(255) NOT NULL,
    drug_name character varying(50) NOT NULL,
    quantity integer NOT NULL,
    "time" time(6) without time zone NOT NULL
);


ALTER TABLE public.drugs OWNER TO brown;

--
-- Name: id_sequence_generator; Type: SEQUENCE; Schema: public; Owner: brown
--

CREATE SEQUENCE public.id_sequence_generator
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.id_sequence_generator OWNER TO brown;

--
-- Name: purchase; Type: TABLE; Schema: public; Owner: brown
--

CREATE TABLE public.purchase (
    purchase_id integer NOT NULL,
    buyer_id integer,
    date date NOT NULL,
    quantity integer NOT NULL,
    "time" time(6) without time zone NOT NULL,
    drug_id integer
);


ALTER TABLE public.purchase OWNER TO brown;

--
-- Name: purchase-sequence; Type: SEQUENCE; Schema: public; Owner: brown
--

CREATE SEQUENCE public."purchase-sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."purchase-sequence" OWNER TO brown;

--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: brown
--

CREATE TABLE public.suppliers (
    supplier_id integer NOT NULL,
    country character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    street_address character varying(255) NOT NULL,
    drug_id integer NOT NULL
);


ALTER TABLE public.suppliers OWNER TO brown;

--
-- Name: suppliers_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: brown
--

ALTER TABLE public.suppliers ALTER COLUMN supplier_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supply-sequence; Type: SEQUENCE; Schema: public; Owner: brown
--

CREATE SEQUENCE public."supply-sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."supply-sequence" OWNER TO brown;

--
-- Name: drugs drugs_pkey; Type: CONSTRAINT; Schema: public; Owner: brown
--

ALTER TABLE ONLY public.drugs
    ADD CONSTRAINT drugs_pkey PRIMARY KEY (id);


--
-- Name: purchase purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: brown
--

ALTER TABLE ONLY public.purchase
    ADD CONSTRAINT purchase_pkey PRIMARY KEY (purchase_id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: brown
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id);


--
-- Name: purchase fkc89kxqwwqky4u6li5rqi4gdod; Type: FK CONSTRAINT; Schema: public; Owner: brown
--

ALTER TABLE ONLY public.purchase
    ADD CONSTRAINT fkc89kxqwwqky4u6li5rqi4gdod FOREIGN KEY (drug_id) REFERENCES public.drugs(id);


--
-- Name: suppliers fkrgbdtmmc5nl6jk6dmkwt113in; Type: FK CONSTRAINT; Schema: public; Owner: brown
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT fkrgbdtmmc5nl6jk6dmkwt113in FOREIGN KEY (drug_id) REFERENCES public.drugs(id);


--
-- PostgreSQL database dump complete
--

